FROM oven/bun:1.2.2-slim

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web




RUN bun install
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN bun run db:migrate

RUN DATABASE_URL=$DATABASE_URL bun run build

EXPOSE 3000

CMD  ["bun","run", "start:frontend"]