FROM oven/bun:1.2.2-slim

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend




RUN bun install
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN bun run db:migrate

EXPOSE 8081

CMD  ["bun","run", "start:backend"]
